// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.customer-directory@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const CUSTOMER_DIRECTORY_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const CUSTOMER_DIRECTORY_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_customer_directory { () => { "{\"capability_id\":\"lenso.customer-directory@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"get_contact\",\"merge_contact\",\"resolve_or_create_email_contact\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_customer_directory_client { () => { "{\"capability_id\":\"lenso.customer-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_customer_directory_client { () => { "{\"capability_id\":\"lenso.customer-directory@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const GET_CONTACT_OPERATION: &str = "get_contact";
pub const MERGE_CONTACT_OPERATION: &str = "merge_contact";
pub const RESOLVE_OR_CREATE_EMAIL_CONTACT_OPERATION: &str = "resolve_or_create_email_contact";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetContactRequest {
    #[serde(rename = "contact_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub contact_id: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetContactResponse {
    #[serde(rename = "contact")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub contact: Contact,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Contact {
    #[serde(rename = "canonical_contact_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub canonical_contact_id: String,
    #[serde(rename = "contact_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub contact_id: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: String,
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: Option<String>,
    #[serde(rename = "email")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub email: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: ContactState,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: String,
}

impl fmt::Debug for Contact {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("Contact")
            .field("canonical_contact_id", &self.canonical_contact_id)
            .field("contact_id", &self.contact_id)
            .field("created_at", &self.created_at)
            .field("display_name", &"<redacted>")
            .field("email", &"<redacted>")
            .field("organization_id", &self.organization_id)
            .field("revision", &self.revision)
            .field("state", &self.state)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ContactState {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "merged")]
    Merged,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetContactError {
    ContactNotFound,
    Forbidden,
    InvalidRequest,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct MergeContactRequest {
    #[serde(rename = "expected_source_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_source_revision: String,
    #[serde(rename = "expected_target_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_target_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "source_contact_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_contact_id: String,
    #[serde(rename = "target_contact_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target_contact_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct MergeContactResponse {
    #[serde(rename = "source_contact")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_contact: Contact,
    #[serde(rename = "target_contact")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target_contact: Contact,
}

#[derive(Clone, Debug, PartialEq)]
pub enum MergeContactError {
    ContactNotActive,
    ContactNotFound,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResolveOrCreateEmailContactRequest {
    #[serde(rename = "display_name")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "email")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub email: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

impl fmt::Debug for ResolveOrCreateEmailContactRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ResolveOrCreateEmailContactRequest")
            .field("display_name", &"<redacted>")
            .field("email", &"<redacted>")
            .field("idempotency_key", &self.idempotency_key)
            .field("organization_id", &self.organization_id)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResolveOrCreateEmailContactResponse {
    #[serde(rename = "contact")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub contact: Contact,
    #[serde(rename = "created")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ResolveOrCreateEmailContactError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct CustomerDirectoryGetContact;
impl RequestCapability for CustomerDirectoryGetContact {
    type Request = GetContactRequest;
    type Response = GetContactResponse;
    type DomainError = GetContactError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_CONTACT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<CustomerDirectoryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_contact(context, request)
    }
}

#[derive(Debug)]
pub struct CustomerDirectoryMergeContact;
impl RequestCapability for CustomerDirectoryMergeContact {
    type Request = MergeContactRequest;
    type Response = MergeContactResponse;
    type DomainError = MergeContactError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != MERGE_CONTACT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<CustomerDirectoryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).merge_contact(context, request)
    }
}

#[derive(Debug)]
pub struct CustomerDirectoryResolveOrCreateEmailContact;
impl RequestCapability for CustomerDirectoryResolveOrCreateEmailContact {
    type Request = ResolveOrCreateEmailContactRequest;
    type Response = ResolveOrCreateEmailContactResponse;
    type DomainError = ResolveOrCreateEmailContactError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RESOLVE_OR_CREATE_EMAIL_CONTACT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<CustomerDirectoryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).resolve_or_create_email_contact(context, request)
    }
}

impl serde::Serialize for GetContactError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ContactNotFound => serializer.serialize_str("contact_not_found"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetContactError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "contact_not_found" => Ok(Self::ContactNotFound),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for MergeContactError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ContactNotActive => serializer.serialize_str("contact_not_active"),
            Self::ContactNotFound => serializer.serialize_str("contact_not_found"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for MergeContactError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "contact_not_active" => Ok(Self::ContactNotActive),
                "contact_not_found" => Ok(Self::ContactNotFound),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ResolveOrCreateEmailContactError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ResolveOrCreateEmailContactError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_get_contact_request(value: &GetContactRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_contact_request(wire: &str) -> Result<GetContactRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_contact_response(value: &GetContactResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_contact_response(wire: &str) -> Result<GetContactResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_contact_error(value: &GetContactError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_contact_error(wire: &str) -> Result<GetContactError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_merge_contact_request(value: &MergeContactRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_merge_contact_request(wire: &str) -> Result<MergeContactRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_merge_contact_response(value: &MergeContactResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_merge_contact_response(wire: &str) -> Result<MergeContactResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_merge_contact_error(value: &MergeContactError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_merge_contact_error(wire: &str) -> Result<MergeContactError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_resolve_or_create_email_contact_request(value: &ResolveOrCreateEmailContactRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resolve_or_create_email_contact_request(wire: &str) -> Result<ResolveOrCreateEmailContactRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_resolve_or_create_email_contact_response(value: &ResolveOrCreateEmailContactResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resolve_or_create_email_contact_response(wire: &str) -> Result<ResolveOrCreateEmailContactResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_resolve_or_create_email_contact_error(value: &ResolveOrCreateEmailContactError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resolve_or_create_email_contact_error(wire: &str) -> Result<ResolveOrCreateEmailContactError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoCustomerDirectoryGetContactResult {
    fn __lenso_into_result(self) -> Result<Result<GetContactResponse, GetContactError>, RuntimeFailure>;
}
impl __LensoIntoCustomerDirectoryGetContactResult for Result<GetContactResponse, GetContactError> {
    fn __lenso_into_result(self) -> Result<Result<GetContactResponse, GetContactError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoCustomerDirectoryGetContactResult for Result<Result<GetContactResponse, GetContactError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetContactResponse, GetContactError>, RuntimeFailure> { self }
}
impl __LensoIntoCustomerDirectoryGetContactResult for Result<GetContactResponse, lenso_plugin_authoring::PluginError<GetContactError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetContactResponse, GetContactError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoCustomerDirectoryGetContactResult for Result<GetContactResponse, CustomerDirectoryGetContactInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetContactResponse, GetContactError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(CustomerDirectoryGetContactInvocationError::Domain(error)) => Ok(Err(error)),
            Err(CustomerDirectoryGetContactInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoCustomerDirectoryMergeContactResult {
    fn __lenso_into_result(self) -> Result<Result<MergeContactResponse, MergeContactError>, RuntimeFailure>;
}
impl __LensoIntoCustomerDirectoryMergeContactResult for Result<MergeContactResponse, MergeContactError> {
    fn __lenso_into_result(self) -> Result<Result<MergeContactResponse, MergeContactError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoCustomerDirectoryMergeContactResult for Result<Result<MergeContactResponse, MergeContactError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<MergeContactResponse, MergeContactError>, RuntimeFailure> { self }
}
impl __LensoIntoCustomerDirectoryMergeContactResult for Result<MergeContactResponse, lenso_plugin_authoring::PluginError<MergeContactError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<MergeContactResponse, MergeContactError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoCustomerDirectoryMergeContactResult for Result<MergeContactResponse, CustomerDirectoryMergeContactInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<MergeContactResponse, MergeContactError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(CustomerDirectoryMergeContactInvocationError::Domain(error)) => Ok(Err(error)),
            Err(CustomerDirectoryMergeContactInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoCustomerDirectoryResolveOrCreateEmailContactResult {
    fn __lenso_into_result(self) -> Result<Result<ResolveOrCreateEmailContactResponse, ResolveOrCreateEmailContactError>, RuntimeFailure>;
}
impl __LensoIntoCustomerDirectoryResolveOrCreateEmailContactResult for Result<ResolveOrCreateEmailContactResponse, ResolveOrCreateEmailContactError> {
    fn __lenso_into_result(self) -> Result<Result<ResolveOrCreateEmailContactResponse, ResolveOrCreateEmailContactError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoCustomerDirectoryResolveOrCreateEmailContactResult for Result<Result<ResolveOrCreateEmailContactResponse, ResolveOrCreateEmailContactError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ResolveOrCreateEmailContactResponse, ResolveOrCreateEmailContactError>, RuntimeFailure> { self }
}
impl __LensoIntoCustomerDirectoryResolveOrCreateEmailContactResult for Result<ResolveOrCreateEmailContactResponse, lenso_plugin_authoring::PluginError<ResolveOrCreateEmailContactError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ResolveOrCreateEmailContactResponse, ResolveOrCreateEmailContactError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoCustomerDirectoryResolveOrCreateEmailContactResult for Result<ResolveOrCreateEmailContactResponse, CustomerDirectoryResolveOrCreateEmailContactInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ResolveOrCreateEmailContactResponse, ResolveOrCreateEmailContactError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(CustomerDirectoryResolveOrCreateEmailContactInvocationError::Domain(error)) => Ok(Err(error)),
            Err(CustomerDirectoryResolveOrCreateEmailContactInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait CustomerDirectoryProvider: fmt::Debug + 'static {
    fn get_contact(&self, context: InvocationContext, request: GetContactRequest) -> NativeRequestFuture<CustomerDirectoryGetContact>;
    fn merge_contact(&self, context: InvocationContext, request: MergeContactRequest) -> NativeRequestFuture<CustomerDirectoryMergeContact>;
    fn resolve_or_create_email_contact(&self, context: InvocationContext, request: ResolveOrCreateEmailContactRequest) -> NativeRequestFuture<CustomerDirectoryResolveOrCreateEmailContact>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_customer_directory {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportCustomerDirectory;
        impl $crate::CustomerDirectoryProvider for $plugin {
        fn get_contact(&self, context: __LensoNativeSupportCustomerDirectory::InvocationContext, request: $crate::GetContactRequest) -> __LensoNativeSupportCustomerDirectory::NativeRequestFuture<$crate::CustomerDirectoryGetContact> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_contact(&plugin, context, request).await;
                $crate::__LensoIntoCustomerDirectoryGetContactResult::__lenso_into_result(result)
            })
        }
        fn merge_contact(&self, context: __LensoNativeSupportCustomerDirectory::InvocationContext, request: $crate::MergeContactRequest) -> __LensoNativeSupportCustomerDirectory::NativeRequestFuture<$crate::CustomerDirectoryMergeContact> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::merge_contact(&plugin, context, request).await;
                $crate::__LensoIntoCustomerDirectoryMergeContactResult::__lenso_into_result(result)
            })
        }
        fn resolve_or_create_email_contact(&self, context: __LensoNativeSupportCustomerDirectory::InvocationContext, request: $crate::ResolveOrCreateEmailContactRequest) -> __LensoNativeSupportCustomerDirectory::NativeRequestFuture<$crate::CustomerDirectoryResolveOrCreateEmailContact> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::resolve_or_create_email_contact(&plugin, context, request).await;
                $crate::__LensoIntoCustomerDirectoryResolveOrCreateEmailContactResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct CustomerDirectoryRequestEndpoint { provider: Rc<dyn CustomerDirectoryProvider> }

#[derive(Debug)]
pub struct CustomerDirectoryEndpoint<P: CustomerDirectoryProvider> { provider: Rc<P>, request_endpoint: CustomerDirectoryRequestEndpoint }
impl<P: CustomerDirectoryProvider> CustomerDirectoryEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn CustomerDirectoryProvider> = provider.clone();
        Self { provider, request_endpoint: CustomerDirectoryRequestEndpoint { provider: request_provider } }
    }
}

impl<P: CustomerDirectoryProvider> NativeRequestEndpoint for CustomerDirectoryEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        GET_CONTACT_OPERATION,
        MERGE_CONTACT_OPERATION,
        RESOLVE_OR_CREATE_EMAIL_CONTACT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            GET_CONTACT_OPERATION => {
                let Ok(request) = request.downcast::<GetContactRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_contact(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            MERGE_CONTACT_OPERATION => {
                let Ok(request) = request.downcast::<MergeContactRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).merge_contact(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RESOLVE_OR_CREATE_EMAIL_CONTACT_OPERATION => {
                let Ok(request) = request.downcast::<ResolveOrCreateEmailContactRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).resolve_or_create_email_contact(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_customer_directory {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::CustomerDirectoryEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_customer_directory {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_customer_directory!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct CustomerDirectoryClient {
    get_contact: NativeRequestHandle<CustomerDirectoryGetContact>,
    merge_contact: NativeRequestHandle<CustomerDirectoryMergeContact>,
    resolve_or_create_email_contact: NativeRequestHandle<CustomerDirectoryResolveOrCreateEmailContact>,
}
impl CustomerDirectoryClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn get_contact(&self, request: GetContactRequest) -> Result<GetContactResponse, CustomerDirectoryGetContactInvocationError> {
        self.get_contact.invoke(GET_CONTACT_OPERATION, request).await
            .map_err(CustomerDirectoryGetContactInvocationError::Runtime)?
            .map_err(CustomerDirectoryGetContactInvocationError::Domain)
    }

    pub async fn get_contact_with_context(&self, context: InvocationContext, request: GetContactRequest) -> Result<GetContactResponse, CustomerDirectoryGetContactInvocationError> {
        self.get_contact.invoke_with_context(GET_CONTACT_OPERATION, context, request).await
            .map_err(CustomerDirectoryGetContactInvocationError::Runtime)?
            .map_err(CustomerDirectoryGetContactInvocationError::Domain)
    }

    pub async fn merge_contact(&self, request: MergeContactRequest) -> Result<MergeContactResponse, CustomerDirectoryMergeContactInvocationError> {
        self.merge_contact.invoke(MERGE_CONTACT_OPERATION, request).await
            .map_err(CustomerDirectoryMergeContactInvocationError::Runtime)?
            .map_err(CustomerDirectoryMergeContactInvocationError::Domain)
    }

    pub async fn merge_contact_with_context(&self, context: InvocationContext, request: MergeContactRequest) -> Result<MergeContactResponse, CustomerDirectoryMergeContactInvocationError> {
        self.merge_contact.invoke_with_context(MERGE_CONTACT_OPERATION, context, request).await
            .map_err(CustomerDirectoryMergeContactInvocationError::Runtime)?
            .map_err(CustomerDirectoryMergeContactInvocationError::Domain)
    }

    pub async fn resolve_or_create_email_contact(&self, request: ResolveOrCreateEmailContactRequest) -> Result<ResolveOrCreateEmailContactResponse, CustomerDirectoryResolveOrCreateEmailContactInvocationError> {
        self.resolve_or_create_email_contact.invoke(RESOLVE_OR_CREATE_EMAIL_CONTACT_OPERATION, request).await
            .map_err(CustomerDirectoryResolveOrCreateEmailContactInvocationError::Runtime)?
            .map_err(CustomerDirectoryResolveOrCreateEmailContactInvocationError::Domain)
    }

    pub async fn resolve_or_create_email_contact_with_context(&self, context: InvocationContext, request: ResolveOrCreateEmailContactRequest) -> Result<ResolveOrCreateEmailContactResponse, CustomerDirectoryResolveOrCreateEmailContactInvocationError> {
        self.resolve_or_create_email_contact.invoke_with_context(RESOLVE_OR_CREATE_EMAIL_CONTACT_OPERATION, context, request).await
            .map_err(CustomerDirectoryResolveOrCreateEmailContactInvocationError::Runtime)?
            .map_err(CustomerDirectoryResolveOrCreateEmailContactInvocationError::Domain)
    }
}

impl CapabilityClient for CustomerDirectoryClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            get_contact: dependencies.one::<CustomerDirectoryGetContact>()?,
            merge_contact: dependencies.one::<CustomerDirectoryMergeContact>()?,
            resolve_or_create_email_contact: dependencies.one::<CustomerDirectoryResolveOrCreateEmailContact>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for CustomerDirectoryClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    get_contact: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<CustomerDirectoryGetContact>()?,
                    merge_contact: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<CustomerDirectoryMergeContact>()?,
                    resolve_or_create_email_contact: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<CustomerDirectoryResolveOrCreateEmailContact>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum CustomerDirectoryGetContactInvocationError {
    Domain(GetContactError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum CustomerDirectoryMergeContactInvocationError {
    Domain(MergeContactError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum CustomerDirectoryResolveOrCreateEmailContactInvocationError {
    Domain(ResolveOrCreateEmailContactError),
    Runtime(RuntimeFailure),
}
